[project]
name = "ml-arena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beartype>=0.20.0",
    "jaxtyping>=0.2.38",
    "numpy>=2.2.3",
    "openskill>=6.0.2",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]
